# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Set the MySQL database name
ENV MYSQL_DATABASE=testdb

# Expose the MySQL port
EXPOSE 3306
